### ISSUE TITLE
Strict Standards Hinweise

### ISSUE THREAD

**Issue by polarpixel** [gn2netwerk/markitup#3]
Folgende Meldungen kommen hier unter PHP 5.4.9 und Redaxo 4.5.0:
- auf der Seite Markitup, Beispielmodule:
  Strict Standards: Only variables should be passed by reference in .../redaxo/include/addons/markitup/pages/modul.inc.php on line 24, 26, 73, 75
- beim Editmodus im Modul:
  Strict Standards: Non-static method a287_markitup::markitup() should not be called statically, assuming $this from incompatible context in .../redaxo/include/classes/class.rex_article_base.inc.php(354) : eval()'d code on line 305

Lg, Peter.

**Comment by jdlx** [comment]
Sollte jetzt behoben sein; die aktuelle master (1.2.0 b3) bitte mal runterladen und testen..

**Comment by polarpixel** [comment]
Jep, klappt! Danke.
Bei RexSEO gibt's ein ähnliches Dingens, schreib ich Dir auch gleich rein.

**Comment by jdlx** [comment]
Hab ich grad schon gemacht.. ;)
