### ISSUE TITLE
$article_clang nicht gesetzt

### ISSUE THREAD

**Issue by tbaddade** [gn2netwerk/markitup#6]
https://github.com/gn2netwerk/markitup/blob/master/pages/setloader.php

 wirft eine Notice: "undefined variable $article_clang"

**Comment by jdlx** [comment]
Welche Zeile? Kannst du das ansonsten irgendwie eingrenzen?

**Comment by tbaddade** [comment]
https://github.com/gn2netwerk/markitup/blob/master/pages/setloader.php#L65
https://github.com/gn2netwerk/markitup/blob/master/pages/setloader.php#L88

**Comment by jdlx** [comment]
Markitup per PHP oder per CSS class aufgerufen?

**Comment by jdlx** [comment]
Ah vergiß es.. sehr grad den Kontext..

**Comment by jdlx** [comment]
fixed
